apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-read-pod
subjects:
  - kind: ServiceAccount
    name: default
    namespace: web
roleRef:
  kind: ClusterRole
  name: read-pv-pod
  apiGroup: rbac.authorization.k8s.io
