apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: app
      image: busybox:1.28.4
      command: ['sh','-c',"echo $(MY_SECRET) && sleep 3600"]
      env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: cert

