apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: custom-node
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: "sakethjakkula6422c.mylabserver.com"
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 2000Mi

