apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: mydaemon
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-con
      labels:
        app: nginx
    spec:
      nodeSelector:
        os: linux
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80



