apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    name: master
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: sakethjakkula6421c.mylabserver.com
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
      

