apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pref
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: pref
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: availability-zone
                    operator: In
                    values:
                      - zone2
#            - weight: 20
#              preference:
#                matchExpressions:
#                - key: share-type
#                  operator: In
#                  values:
#                    - shared
      containers:
        - args:
          - sleep
          - "99999"
          image: busybox
          name: main
