apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvtest
spec:
  capacity:
    storage: 2G
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: "local"
  hostPath:
    path: /data


