apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hdd
spec:
  storageClassName: fast
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageos:
    volumeName: db-data
    fsType: xfs
