apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webrs
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: podrs
      labels:
        tier: frontend
    spec:
      containers:
        - name: contrs
          image: linuxacademycontent/kubeserve
