apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: pd
      labels:
        tier: frontend
    spec:
      containers:
        - image: linuxacademycontent/kubeserve:v1
          name: cont

