apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  nodeSelector:
    kubernetes.io/hostname: "sakethsakethjakkula6422c.mylabserver.com"
  containers:
    - image: busybox
      name: busybox
      command: ["dd", "if=/dev/zero", "of=/dev/null"]
