apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  volumes:
    - name: secretvolume
      secret:
        secretName: appsecret
  containers:
    - image: busybox
      name: busybox
      command: ['sh', '-c', "echo Hello, Kubernetes! && sleep 3600"]
      volumeMounts:
        - name: secretvolume
          mountPath: /etc/secret

