apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  volumes:
    - name: secretvolume
      secret:
        secretName: appsecret

  containers:
    - name: app
      image: busybox:1.28.4
      command: ['sh','-c',"sleep 3600"]
      volumeMounts:
        - name: secretvolume
          mountPath: /etc/certs
