apiVersion: v1
kind: Pod
metadata:
    name: test1-pd
spec:
  containers:
  - image: nginx
    name: test-container1
    volumeMounts:
    - mountPath: /app
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
